#!/bin/sh

for arg in "$@"; do
    echo "\nUploading ${arg} to ${TRACKER_URL}..."
    curl -X PUT "${TRACKER_URL}/upload" \
	 -H "X-SAR-Token: $TRACKER_API_KEY" \
	 -H "Content-Type: application/json" \
	 -d @"$arg"
    echo "\n\n"
done

